### ISSUE TITLE
Changelog is empty

### ISSUE THREAD

**Issue by HadesArchitect** [mongrate/mongrate.com#1]
![image](https://cloud.githubusercontent.com/assets/1742301/16302512/d546c7aa-394b-11e6-92ff-67e648b08123.png)

**Comment by amyboyd** [comment]
Oops! Will fix this when I'm back at my laptop in 10 mins :)

**Comment by amyboyd** [comment]
Fixed.

![image](https://cloud.githubusercontent.com/assets/398210/16302980/016bfbf8-3946-11e6-9e3b-ea97c873cde5.png)

**Comment by HadesArchitect** [comment]
Works as a charm.

btw thanks for the lib.
